---
# Copyright (c) IBM Corporation 2020 

# This sample playbook demonstrates how to use the role sa_delete_dynamic_resource.
# Example:
# ansible-playbook -i hosts sample_pb_delete_dynres.yaml
# or: when ansible.cfg contains a default for the inventory it can be simplified to
# ansible-playbook sample_pb_delete_dynres.yaml
- name: find, stop, and delete an SA resource
  hosts: sampleHost1
  gather_facts: no
  collections:
    - ibm.ibm_zos_automation
  vars_files:
    - ./vars/vars.yaml
  vars_prompt:
    - name: username
      prompt: "Enter your username"
      private: no

    - name: password
      prompt: "Enter your password"
      private: yes    
  tasks:
    - include_role:
        name: sa_delete_dynamic_resource
...
